from __future__ import annotations

from enum import StrEnum


class ReasonCode(StrEnum):
    MIN_TOTAL_COST = "MIN_TOTAL_COST"
    EARLIEST_FEASIBLE = "EARLIEST_FEASIBLE"
    PRIORITY_DEADLINE = "PRIORITY_DEADLINE"
    PROTECTED_INFERENCE = "PROTECTED_INFERENCE"
    RENEWABLE_SURPLUS = "RENEWABLE_SURPLUS"
    GRID_CAPACITY = "GRID_CAPACITY"
    BATTERY_RESERVE = "BATTERY_RESERVE"
    SOVEREIGNTY = "SOVEREIGNTY"
    FALLBACK = "FALLBACK"
